**This is used to transform our data in python and make data cleaning procedure**

In [37]:
import pandas as pd 
import calendar

In [25]:
data = pd.read_csv("../data/raw/Global_Mobile_Prices_2025_Extended.csv")

In [26]:
data.head(5)

,brand,model,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,5g_support,os,processor,rating,release_month,year
0,Oppo,A98 111,855,16,128,108,6000,6.6,33,Yes,Android,Helio G99,3.8,February,2025
1,Realme,11 Pro+ 843,618,6,128,64,4500,6.9,100,Yes,Android,Tensor G4,4.4,August,2025
2,Xiaomi,Redmi Note 14 Pro 461,258,16,64,64,4000,6.8,44,Yes,Android,A18 Pro,4.1,March,2025
3,Vivo,V29e 744,837,6,512,48,4500,6.0,65,Yes,Android,Exynos 2400,4.1,August,2025
4,Apple,iPhone 16 Pro Max 927,335,12,128,200,5000,6.9,100,Yes,iOS,Dimensity 9300,3.5,February,2025

**First of all steps we have to check for existence of null values.**

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              1000 non-null   object
 1   model              1000 non-null   object
 2   price_usd          1000 non-null   int64
 3   ram_gb             1000 non-null   int64
 4   storage_gb         1000 non-null   int64
 5   camera_mp          1000 non-null   int64
 6   battery_mah        1000 non-null   int64
 7   display_size_inch  1000 non-null   float64
 8   charging_watt      1000 non-null   int64
 9   5g_support         1000 non-null   object
 10  os                 1000 non-null   object
 11  processor          1000 non-null   object
 12  rating             1000 non-null   float64
 13  release_month      1000 non-null   object
 14  year               1000 non-null   int64
dtypes: float64(2), int64(7), object(6)
memory usage: 117.3+ KB

In [28]:
data.isnull().sum()

brand                0
model                0
price_usd            0
ram_gb               0
storage_gb           0
camera_mp            0
battery_mah          0
display_size_inch    0
charging_watt        0
5g_support           0
os                   0
processor            0
rating               0
release_month        0
year                 0
dtype: int64

In [29]:
data.duplicated().sum()  #checking for duplicate values

np.int64(0)

In [30]:
data.dtypes

brand                 object
model                 object
price_usd              int64
ram_gb                 int64
storage_gb             int64
camera_mp              int64
battery_mah            int64
display_size_inch    float64
charging_watt          int64
5g_support            object
os                    object
processor             object
rating               float64
release_month         object
year                   int64
dtype: object

In [32]:
data['5g_support'] = data['5g_support'].map({'Yes': True, 'No': False}) #chage yes no to boolean true false

In [ ]:
data['5g_support'].unique()

In [34]:
data['os'].unique()

array(['Android', 'iOS'], dtype=object)

In [35]:
data['release_month'].unique()

array(['February', 'August', 'March', 'May', 'April', 'November', 'July',
       'December', 'October', 'January', 'June', 'September'],
      dtype=object)

In [39]:
months_map = {m: i for i, m in enumerate(calendar.month_name) if m}
data['release_month_num'] = data['release_month'].map(months_map)

In [40]:
data[['release_month', 'release_month_num']].head(12)

   release_month  release_month_num
0       February                  2
1         August                  8
2          March                  3
3         August                  8
4       February                  2
5            May                  5
6          April                  4
7       November                 11
8           July                  7
9          March                  3
10         April                  4
11        August                  8

In [41]:
data['processor'].unique()[:20]

array(['Helio G99', 'Tensor G4', 'A18 Pro', 'Exynos 2400',
       'Dimensity 9300', 'Snapdragon 6 Gen 1', 'Snapdragon 8 Gen 3',
       'Snapdragon 7+ Gen 2'], dtype=object)